project:
  type: website
  output-dir: docs

website:
  title: "Kim Young Jin"
  google-analytics: "G-PJQ5ZH4KTP"
  navbar:
    left:
      - text: CV
        href: https://drive.google.com/file/d/1iKxuw4TnR15k_sLqi5q4o5845Gvz83Ft/view?usp=sharing
    right:
      - icon: github
        href: https://github.com/jugheadjones10
      - icon: twitter
        href: https://twitter.com/yjmemos
format:
  html:
    theme: united
    css: styles.css
