project:
  type: website
  output-dir: docs

website:
  title: "Kim Young Jin"
  google-analytics: "G-PJQ5ZH4KTP"
  navbar:
    left:
      - writing.qmd
      - learning.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/jugheadjones10
      - icon: twitter
        href: https://twitter.com/yjmemos
format:
  html:
    theme: litera
    css: styles.css
