---
title: "Ambitious but at peace"
date: "2024-05-17"
---

For most of my life I've felt a deep discontent myself.

We hear a lot of advice to "love yourself", have a "kind inner voice", and so on. I've always felt these were coping mechanisms, anesthesia to dull the pain of reality. Better to embrace the pain, I thought. Invigorate yourself with the fury of self-hatred and envy. Only the unambitious are content with the warm fuzziness of satisfaction. It's like what they always say: the most successful people contain within them a contradiction - near delusional levels of self-belief fueled by an intense anxiety around never being good enough.

I'm still in my early twenties, but my stance has changed somewhat. Ambition doesn't mean you need to constantly hate where you are at. Ambition is about the magnitude of your end goals, not your mental state on the way there. If you could take a different road to the same destination, one that preserves your peace of mind, why wouldn't you?

And that other, more peaceful road, might get you to your goal faster. With peace of mind, you can keep going, day in and day out. By prioritising peace of mind, you are making the choice to run a marathon instead of a sprint. Who will be fresh-headed and grinding, ten years from now? The ambitious one who looks at every failure of his as the biggest catastrophe he has ever faced? Or the ambitious one who controls what is within his control, lets go of what is not, and is at peace with himself?

Real strength comes from knowing that there is absolutely nothing that can happen to you that will stop you from continuing forward.

[Hacker news discussion](https://news.ycombinator.com/item?id=40389480)