---
title: "Quick thoughts on 'Mere Christianity' by C.S Lewis"
date: "2024-06-03"
---

### 1. Pride

C.S Lewis talks at length about how Pride is one of those things that is easiest to criticize in others, but hardest to find in yourself. 

It is effortless to despise the hubris of others, to whisper of their wicked arrogance behind their backs. But the great irony is that those who most despise Pride in others are in fact the most prideful of the bunch. You cannot bear to see a friend boast and receive all the attention, because you secretly wish it were you in the spotlight instead. You cannot bear to see a neighbour be successful, because you wish it were you claiming success instead.

I had a friend who always had that cocky air about him. It used to bother me a bit too much. I thought, "What good did he do, that he has the right to strut about like that?" Implicit in this statement is my belief that my friend is not as good as he makes himself out to be. It bothered me so much, because it pricked at my own outsized Pride.

A low self-esteem, and insecurity, and self-hate - it may seem paradoxical, but now I see that these, too, are manifestations of Pride. When you cannot accept who you are - when you refuse to let go of ambition - every small blemish is reason for you to bemoan your wretched self. Why am I so dumb? Why am I so slow? A great self-loathing grows from this stream of negativity.

But if you so hate these shortcomings in yourself, how much more would you despise it in others? All the people who have even less than what you have - what about them? The secretly prideful soul derives a twisted satisfaction from looking down at those beneath him. 

"At least I am better than them."

"Dull as I may be, at least I am less dull than them." 

Resentment at those above you translates into hate towards youself, and a superiority complex at those beneath you. 

Only when you embrace yourself, as you are, can you embrace others, as they are.

### 2. Morality

C.S Lewis points to the moral compass within every one of us as proof of God. As physical objects obey gravity, so do we obey the moral law. But unlike gravity, we are given a choice. Our free will means that every man, every day, makes decisions that break or keep the moral law.

I would like to believe in this. It is a compelling argument, except for that one annoying possibility that our morality comes from our Biology, not from some objective moral truth. What if evolution selected for those populations that developed emotional responses to morally "right" or "wrong" actions? Certainly we can see how it might have helped some popluations survive and not others. If that is the case, we cannot argue for an objective moral truth by only "introspecting"
on our consciences.

### 3. Free will

And that, of course, leads to the thorny issue of free will. Without free will, none of Christianity makes sense. How can we have free will? How would free will even work? In some sense, there are echoes of the "First Cause Argument" for the existence of God. It says that everything must have a cause, and so the Universe also needs to have a "first cause". Only God can be that first cause, because God is the only thing that can exist without itself having a cause (this argument is actually
flawed - the basis is that everything must have a cause, so we are contradicting ourselves by saying that God does not have a cause). 

Could we argue in a similar way about free will? That everything needs to have a cause, but free will, as something given by God, does not have a "cause" and is solely the product of our self-determining souls?

What if the day comes when we fully understand how human consciousness works, and it turns out that we actually *are* just machines running on good old cause and effect, living under the illusion of autonomy?

### 4. I hope it is all true

One part of me is sceptical, but another side of me wishes it were all true. I am starting to see the consequences that an "amoral" life and mindset is having on my psyche. It is not pretty. There is a constant feeling of emptiness, a desperate hope that there is more to life than my petty ambitions and the little games that we all play. 

One can only pray. But how can I pray, if I know no God?

### Epilogue: questions and discussion

Here are some questions that I would like to ask practicing Christians.

- If it really is true that there is a Heaven and a Hell, shouldn't Christians be spending all their time trying to convert non-believers? I know that changing someone's belief cannot be forced. It is not something you can make happen simply by investing time. But surely there are other things to do, like trying to build more churches, etc.? Are Christians allowed to be leisureful if they know full well that there still remain some souls who will suffer for eternity in Hell? To some bystanders, it might seem like Christans are content to "milk the cow", so to speak, and live out their lives enjoying the peace of mind that religion brings.

- I don't understand what it means to "receive God's help" or be "tempted by the Devil". I understand that we have been given free will by God, but also that we can influence things by praying. But if God can insert thoughts into people's minds, then don't those people *not* have free will? In fact, I thought God is allowing bad things to happen in the world precisely because he has given us free will and does not want to intervene. How come Christians are given a chance to circumvent this restriction through prayer? 

- There are many interpretations of the Bible. There are many interpretations of Theology. But there can only be one Truth, right? Some of these interpretations have to be wrong. Can one be "saved" even if he believes in a slightly "wrong" interpretation? If not, then shouldn't finding this one correct interpretation be the primary pursuit of Christians? But then again, *can* there even be one definite interpretation of something literary like the Bible? 

  If it is not possible to converge to one correct interpretation, but there is only one True reality, does that mean the best we can do is hope we have joined the correct denomination and pray for the best? That seems awfully random and cruel of God.

- One thing that bugs me is that at the end of the day, everything kind of revolves around *feelings*, or, more precisely, *perception*. It all depends on the exact thing that your consciousness is experiencing. If that thing is strong enough to convince you of God's existence, the story ends there, no one can convince you otherwise. It's just that so many aspects of Christian life seem to revolve around these "perceptions": "God touched my heart", "God helped me love my brethren", "God guided me take this path". I mean, yeah, you could say that you really did feel God and I wouldn't be able to refute that because I do not know your consciousness. But we do know that feelings are caused by complex biochemical processes in the body. 

  We do not yet understand consciousness enough to map *every single* conscious experience to some physical state that the body is in, but what if all these "feelings" turn out to be emotions caused by certain psychological states that social structures like Churches cause in you? 
  
  Unless - and this is an interesting idea - the very mechanisms of Biology were hand-crafted by God to cause these feelings. In other words, it's not emotions *causing* spiritual feelings - it's that God engineered the world so that doing spiritual things will, through Biology, cause your consciousness to experience those most edifying feelings of being in touch with God.







