---
title: "Trying to get good at math and science"
date: "2024-05-19"
---

<!-- In my primary school years, I did well at science and math simply by caring more about grades than my peers. It was pure conscientious at play. On hindsight there were probably a lot of people more gifted than me in my class, but 





I have a vision of learning Math and Science. -->

Getting good at Math and Science occupies a hazy middle ground between memory and understanding, between mechanical and conceptual understanding. Memory and understanding are also
not straightforward. There are layers. Understanding might beget an Aha! moment that slips cunningly away, tricking us into reassurance. Understanding once, does not mean you understand
forever. So inevitably there is a component of memory in understanding. But there are also some types of understanding that are more "meta" - broad strokes that set the stage and context behind so many of a subject's concepts. This kind of understanding can act like a pinboard for the rest of the subject, helping you see the connections and draw the lines.

And further still, there is a type of understanding that can only come from practice, and this is the most difficult to acquire of them all. It can be fun, and even easy, to watch
beautiful 3B1B videos or read textbooks and "understand" their theorems. You might even have memorized most of the concepts presented. But does that mean you can apply them to problems?

To solve the really challening problems, you need to twist and distort concepts, fit them together this way and that. If understanding gained from reading is like listening to your
Dad explain how to balance on a 2-wheel bicycle, understanding gained from practice is like using every ounce of dexterity and physical instinct in your body to balance, balance,
somehow try to balance!

Reading pushes information into your brain. Practice pulls from it. As strands of half-formed ideas are wrenched from your brain, they tangle with one another and with concepts wholly
unconnected from what you may have been learning about. It is through that process that understanding starts to show hints of becoming **yours**.



I have been thinking about how to make it easier to learn from textbooks.

How can we use LLMs to augment the learning process of a textbook? First, we need to accept that learning is never going to become "easy". You need to put in the hours and the
concentration, and no AI is going to do that for you. What it CAN do is act like a tool to streamline how you practice questions and try to remember content.

A sort of "ecosystem" for autodidacts? Online forum for crowdsourced answers for textbooks, and an LLM-powered textbook reader for creating flashcards and knowledge graphs
for textbooks. Maybe this can be community-driven as well? No, but maybe that defeats the purpose. Everyone just generates their own personalized flashcards, for their own learning.
